{\rtf1\ansi\ansicpg1252\cocoartf1404\cocoasubrtf470
{\fonttbl\f0\fnil\fcharset0 Menlo-Regular;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs22 \cf0 \CocoaLigature0 sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")\
- So I changed port to 3306, and then I changed it back to 8889, which is my real port number. Error no longer exists.\
\
  File "/Users/sushmamangalapally/Documents/CodingDojo/Python/python_stack/flask_MySQL/mysqlconnection.py", line 9, in __init__\
    'database': whar, # we got db as an argument\
NameError: global name 'whar' is not defined\
- I changed database name from db to \'93whar\'94, which I got the above results. The error tells us that the name \'93what\'94 for the database is not defined.\
\
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (1045, "Access denied for user 'who'@'localhost' (using password: YES)")\
- I changed user name from root to \'93who\'94, which I got the above results. The error tells us that the access to \'93who\'94 is denied.\
}